### ISSUE TITLE
Mohon bantuan order tidak berubah secara otomatis- woocommerce

### ISSUE THREAD

**Issue by ahmadalfiansdb** [veritrans/veritrans-php#102]
```
> 2020-04-28T04:03:00+00:00 CRITICAL Uncaught Error: Call to a member function get_payment_method() on boolean in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php:76
> Stack trace:
> #0 /home/kasturia/public_html/wp-includes/class-wp-hook.php(287): WC_Gateway_Midtrans_Notif_Handler->midtrans_response('')
> #1 /home/kasturia/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
> #2 /home/kasturia/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
> #3 /home/kasturia/public_html/wp-content/plugins/woocommerce/includes/class-wc-api.php(148): do_action('woocommerce_api...')
> #4 /home/kasturia/public_html/wp-includes/class-wp-hook.php(287): WC_API->handle_api_requests(Object(WP))
> #5 /home/kasturia/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
> #6 /home/kasturia/public_html/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
> #7 /home/kasturia/public_html/wp-includes/class-wp.php(388): do_action_ref_array('parse_req in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php on line 76
> 
> 2020-04-28T04:04:11+00:00 CRITICAL Uncaught Error: Call to a member function get_payment_method() on boolean in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php:76
> Stack trace:
> #0 /home/kasturia/public_html/wp-includes/class-wp-hook.php(287): WC_Gateway_Midtrans_Notif_Handler->midtrans_response('')
> #1 /home/kasturia/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
> #2 /home/kasturia/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
> #3 /home/kasturia/public_html/wp-content/plugins/woocommerce/includes/class-wc-api.php(148): do_action('woocommerce_api...')
> #4 /home/kasturia/public_html/wp-includes/class-wp-hook.php(287): WC_API->handle_api_requests(Object(WP))
> #5 /home/kasturia/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
> #6 /home/kasturia/public_html/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
> #7 /home/kasturia/public_html/wp-includes/class-wp.php(388): do_action_ref_array('parse_req in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php on line 76
> 
> 2020-04-28T04:11:09+00:00 CRITICAL Uncaught Error: Call to a member function get_payment_method() on boolean in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php:76
> Stack trace:
> #0 /home/kasturia/public_html/wp-includes/class-wp-hook.php(287): WC_Gateway_Midtrans_Notif_Handler->midtrans_response('')
> #1 /home/kasturia/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
> #2 /home/kasturia/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
> #3 /home/kasturia/public_html/wp-content/plugins/woocommerce/includes/class-wc-api.php(148): do_action('woocommerce_api...')
> #4 /home/kasturia/public_html/wp-includes/class-wp-hook.php(287): WC_API->handle_api_requests(Object(WP))
> #5 /home/kasturia/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
> #6 /home/kasturia/public_html/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
> #7 /home/kasturia/public_html/wp-includes/class-wp.php(388): do_action_ref_array('parse_req in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php on line 76
> 
> 2020-04-28T04:29:14+00:00 CRITICAL Uncaught Error: Call to a member function get_payment_method() on boolean in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php:76
> Stack trace:
> #0 /home/kasturia/public_html/wp-includes/class-wp-hook.php(287): WC_Gateway_Midtrans_Notif_Handler->midtrans_response('')
> #1 /home/kasturia/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
> #2 /home/kasturia/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
> #3 /home/kasturia/public_html/wp-content/plugins/woocommerce/includes/class-wc-api.php(148): do_action('woocommerce_api...')
> #4 /home/kasturia/public_html/wp-includes/class-wp-hook.php(287): WC_API->handle_api_requests(Object(WP))
> #5 /home/kasturia/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
> #6 /home/kasturia/public_html/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
> #7 /home/kasturia/public_html/wp-includes/class-wp.php(388): do_action_ref_array('parse_req in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php on line 76
> 
> 2020-04-28T05:02:15+00:00 CRITICAL Uncaught Error: Call to a member function get_payment_method() on boolean in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php:76
> Stack trace:
> #0 /home/kasturia/public_html/wp-includes/class-wp-hook.php(287): WC_Gateway_Midtrans_Notif_Handler->midtrans_response('')
> #1 /home/kasturia/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
> #2 /home/kasturia/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
> #3 /home/kasturia/public_html/wp-content/plugins/woocommerce/includes/class-wc-api.php(148): do_action('woocommerce_api...')
> #4 /home/kasturia/public_html/wp-includes/class-wp-hook.php(287): WC_API->handle_api_requests(Object(WP))
> #5 /home/kasturia/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
> #6 /home/kasturia/public_html/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
> #7 /home/kasturia/public_html/wp-includes/class-wp.php(388): do_action_ref_array('parse_req in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php on line 76
> 
> 2020-04-28T07:05:52+00:00 CRITICAL Uncaught Exception: Midtrans Error (404): Transaction doesn't exist. in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php:111
> Stack trace:
> #0 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php(22): Midtrans\ApiRequestor::remoteCall('https://api.mid...', 'Mid-server-jMGS...', false, false)
> #1 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Transaction.php(23): Midtrans\ApiRequestor::get('https://api.mid...', 'Mid-server-jMGS...', false)
> #2 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Notification.php(26): Midtrans\Transaction::status('22b16711-69c2-4...')
> #3 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-api.php(140): Midtrans\Notification->__construct()
> #4 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php( in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php on line 111
> 
> 2020-04-28T07:10:31+00:00 CRITICAL Uncaught Exception: Midtrans Error (404): Transaction doesn't exist. in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php:111
> Stack trace:
> #0 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php(22): Midtrans\ApiRequestor::remoteCall('https://api.mid...', 'Mid-server-jMGS...', false, false)
> #1 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Transaction.php(23): Midtrans\ApiRequestor::get('https://api.mid...', 'Mid-server-jMGS...', false)
> #2 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Notification.php(26): Midtrans\Transaction::status('22b16711-69c2-4...')
> #3 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-api.php(140): Midtrans\Notification->__construct()
> #4 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php( in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php on line 111
> 
> 2020-04-28T09:02:14+00:00 CRITICAL Uncaught Exception: Midtrans Error (404): Transaction doesn't exist. in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php:111
> Stack trace:
> #0 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php(22): Midtrans\ApiRequestor::remoteCall('https://api.mid...', 'Mid-server-jMGS...', false, false)
> #1 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Transaction.php(23): Midtrans\ApiRequestor::get('https://api.mid...', 'Mid-server-jMGS...', false)
> #2 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Notification.php(26): Midtrans\Transaction::status('057a72e6-493e-4...')
> #3 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-api.php(140): Midtrans\Notification->__construct()
> #4 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php( di /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php pada baris 111
> 
> 2020-04-28T09:47:15+00:00 CRITICAL Uncaught Exception: Midtrans Error (404): Transaction doesn't exist. in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php:111
> Stack trace:
> #0 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php(22): Midtrans\ApiRequestor::remoteCall('https://api.mid...', 'Mid-server-jMGS...', false, false)
> #1 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Transaction.php(23): Midtrans\ApiRequestor::get('https://api.mid...', 'Mid-server-jMGS...', false)
> #2 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Notification.php(26): Midtrans\Transaction::status('057a72e6-493e-4...')
> #3 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-api.php(140): Midtrans\Notification->__construct()
> #4 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php( di /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php pada baris 111
> 
> 2020-04-28T09:50:03+00:00 CRITICAL Uncaught Exception: Midtrans Error (404): Transaction doesn't exist. in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php:111
> Stack trace:
> #0 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php(22): Midtrans\ApiRequestor::remoteCall('https://api.mid...', 'Mid-server-jMGS...', false, false)
> #1 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Transaction.php(23): Midtrans\ApiRequestor::get('https://api.mid...', 'Mid-server-jMGS...', false)
> #2 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Notification.php(26): Midtrans\Transaction::status('3ecd0692-86ae-4...')
> #3 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-api.php(140): Midtrans\Notification->__construct()
> #4 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php( di /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php pada baris 111
> 
> 2020-04-28T09:53:46+00:00 CRITICAL Uncaught Exception: Midtrans Error (404): Transaction doesn't exist. in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php:111
> Stack trace:
> #0 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php(22): Midtrans\ApiRequestor::remoteCall('https://api.mid...', 'Mid-server-jMGS...', false, false)
> #1 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Transaction.php(23): Midtrans\ApiRequestor::get('https://api.mid...', 'Mid-server-jMGS...', false)
> #2 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Notification.php(26): Midtrans\Transaction::status('3ecd0692-86ae-4...')
> #3 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-api.php(140): Midtrans\Notification->__construct()
> #4 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php( di /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php pada baris 111
> 
> 2020-04-28T10:01:24+00:00 CRITICAL Uncaught Exception: Midtrans Error (404): Transaction doesn't exist. in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php:111
> Stack trace:
> #0 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php(22): Midtrans\ApiRequestor::remoteCall('https://api.mid...', 'Mid-server-jMGS...', false, false)
> #1 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Transaction.php(23): Midtrans\ApiRequestor::get('https://api.mid...', 'Mid-server-jMGS...', false)
> #2 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Notification.php(26): Midtrans\Transaction::status('057a72e6-493e-4...')
> #3 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-api.php(140): Midtrans\Notification->__construct()
> #4 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php( di /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php pada baris 111
> 
> 2020-04-28T10:42:45+00:00 CRITICAL Uncaught Exception: Midtrans Error (404): Transaction doesn't exist. in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php:111
> Stack trace:
> #0 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php(22): Midtrans\ApiRequestor::remoteCall('https://api.mid...', 'Mid-server-jMGS...', false, false)
> #1 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Transaction.php(23): Midtrans\ApiRequestor::get('https://api.mid...', 'Mid-server-jMGS...', false)
> #2 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Notification.php(26): Midtrans\Transaction::status('ec4fd00c-fdef-4...')
> #3 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-api.php(140): Midtrans\Notification->__construct()
> #4 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php( di /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php pada baris 111
> 
> 2020-04-28T11:04:15+00:00 CRITICAL Uncaught Exception: Midtrans Error (404): Transaction doesn't exist. in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php:111
> Stack trace:
> #0 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php(22): Midtrans\ApiRequestor::remoteCall('https://api.mid...', 'Mid-server-jMGS...', false, false)
> #1 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Transaction.php(23): Midtrans\ApiRequestor::get('https://api.mid...', 'Mid-server-jMGS...', false)
> #2 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Notification.php(26): Midtrans\Transaction::status('3ecd0692-86ae-4...')
> #3 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-api.php(140): Midtrans\Notification->__construct()
> #4 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php( di /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php pada baris 111
> 
> 2020-04-28T11:25:45+00:00 CRITICAL Uncaught Exception: Midtrans Error (404): Transaction doesn't exist. in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php:111
> Stack trace:
> #0 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php(22): Midtrans\ApiRequestor::remoteCall('https://api.mid...', 'Mid-server-jMGS...', false, false)
> #1 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Transaction.php(23): Midtrans\ApiRequestor::get('https://api.mid...', 'Mid-server-jMGS...', false)
> #2 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Notification.php(26): Midtrans\Transaction::status('3ecd0692-86ae-4...')
> #3 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-api.php(140): Midtrans\Notification->__construct()
> #4 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php( di /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php pada baris 111
> 
> 2020-04-28T11:42:21+00:00 CRITICAL Uncaught Exception: Midtrans Error (404): Transaction doesn't exist. in /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php:111
> Stack trace:
> #0 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php(22): Midtrans\ApiRequestor::remoteCall('https://api.mid...', 'Mid-server-jMGS...', false, false)
> #1 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Transaction.php(23): Midtrans\ApiRequestor::get('https://api.mid...', 'Mid-server-jMGS...', false)
> #2 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/Notification.php(26): Midtrans\Transaction::status('057a72e6-493e-4...')
> #3 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-api.php(140): Midtrans\Notification->__construct()
> #4 /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway-notif-handler.php( di /home/kasturia/public_html/wp-content/plugins/midtrans-woocommerce/lib/midtrans/Midtrans/ApiRequestor.php pada baris 111


```

Mohon bantuannya, merchant id, serverkey, clientkey terisi dengan baik, di hari sebelumnya perubahan metode payment otomati di woocommerce berjalan lancar, namun beberapa hari kemudian tidak berjalan dengan baik. order tidak berubah otomatis menjadi complete, namun di dashboard midtrans payment masuk.

saya coba menggunakan sandbox, saya kembalikan thema ke awal dan menonaktifkan plugin yang ada tetap saja tidak ada perubahan. saya coba ulang method pembayarannya 
![image](https://user-images.githubusercontent.com/52006486/80825436-983e4200-8c0a-11ea-89f0-2e06007243b5.png)

sudah settlement
![image](https://user-images.githubusercontent.com/52006486/80825524-cc196780-8c0a-11ea-860c-96d49e6e5bc3.png)

namun tidak terjadi apa apa
![image](https://user-images.githubusercontent.com/52006486/80825715-231f3c80-8c0b-11ea-8bd3-0ab819c2ee50.png)

**Comment by aalexanderkevin** [comment]
Hi pak @ahmadalfiansdb  sepertinya kurang tepat bila issue pada plugin midtrans-woocommerce disampaikan pada repo ini.

Untuk pertanyaan terkait plugin woocommerce, boleh langsung disampaikan pada repo yang ini ya https://github.com/veritrans/SNAP-Woocommerce/issues
terimakasih

**Comment by ahmadalfiansdb** [comment]
oke baik terimakasih ternyata sudah ada solusi disana
